name: Docker Compose Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker Compose services
      run: docker-compose -f docker-compose-test.yaml build

    # Optionally, you can add a step to bring up the services
    # - name: Bring up the Docker Compose services
    #   run: docker-compose -f docker-compose-test.yaml up -d