name: Docker Compose Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker Compose services
      run: docker build -t minio-flask-webhook .
      
    - name: List Containers
      run: docker ps -a 